fix: mock UDP streamer: don't reset sequence numbers when decimation changes
Otherwise, it's possible to push packets with duplicate sequence onto
the packet queues, which gives exceptions of the following form:

    await crs.set_decimation(stage=5);await crs.set_decimation(stage=6)
    Unhandled exception in Periscope (CLI mode):
    Traceback (most recent call last):
      File "/home/gsmecher/crs/rfmux/rfmux/tools/periscope/tasks.py", line 73, in run
        self._process_received_packet(data)
      File "/home/gsmecher/crs/rfmux/rfmux/tools/periscope/tasks.py", line 67, in _process_received_packet
        self.queue.put((pkt.seq, pkt))
      File "/home/gsmecher/.local/share/uv/python/cpython-3.12.2-linux-x86_64-gnu/lib/python3.12/queue.py", line 150, in put
        self._put(item)
      File "/home/gsmecher/.local/share/uv/python/cpython-3.12.2-linux-x86_64-gnu/lib/python3.12/queue.py", line 236, in _put
        heappush(self.queue, item)
    TypeError: '<' not supported between instances of 'rfmux.streamer._receiver.ReadoutPacket' and 'rfmux.streamer._receiver.ReadoutPacket'

This occurs because packets are pushed onto the queue as (seq, pkt)
tuples. When duplicate sequence numbers show up, the python queue
implementation attempts to tiebreak the sequence comparison using pkt
comparisons. That's a sane thing to do, but requires a packet comparison
operator (which isn't implemented in the c++). In this case, we
shouldn't be seeing duplicate packets in the first place.