fix(streamer): update libfmt to avoid MacOS build regression
clang++ fails to build libfmt as follows:

	/usr/bin/clang++  [...] /var/folders/8j/sfr9qqcj73j4p6nhwcfpr0th0000gn/T/tmpq6rhglcp/build/_deps/fmt-src/src/os.cc
	[...]/fmt-src/src/os.cc:176:35: error: call to consteval function 'fmt::basic_format_string<char, const char *>::basic_format_string<FMT_COMPILE_STRING, 0>' is not a constant expression